web-server-doc/web-server/scribblings/dispatch-server.scrbl
web-server-doc/web-server/scribblings/launch.scrbl
web-server-doc/web-server/scribblings/web-server-unit.scrbl
web-server-lib/info.rkt
web-server-lib/web-server/private/dispatch-server-sig.rkt
web-server-lib/web-server/private/dispatch-server-unit.rkt
web-server-lib/web-server/private/dispatch-server-with-connect-unit.rkt
web-server-lib/web-server/private/launch.rkt
web-server-lib/web-server/private/raw-dispatch-server-connect-unit.rkt
web-server-lib/web-server/servlet-dispatch.rkt
web-server-lib/web-server/web-server-unit.rkt
web-server-lib/web-server/web-server.rkt

These changes restore compatibility with the v6.1.1 release while preserving corrected HTTPS support and the new connection-conversion hook.
Since the release and current development version are mutually incompatible, the changes here favor the release, changing the names of arguments and signatures added since v6.1.1.
The `web-server@` and `dispatch-server@` units have the same imports as before, while new `web-server-with-connect@` and `dispatch-server-with-connect@` units import the new hook. (Backward compatibility would be easier and nicer if the unit system supported optional imports with default implementations.)

restore old `#:tcp@` and `tcp^` arguments/imports, rename new

---

web-server-lib/web-server/http/request-structs.rkt

request-structs.rkt only requires net/url-structs (to provide `url?`).
This stops a lot of heavy, deeper requirements such as http-client, url-connect, mzssl, win32-ssl, gunzip, port, tcp to be omitted.
These are unnecessary when we’re simply manipulating request _structures_

request-structs.rkt : don’t need all of net/url

---

web-server-lib/web-server/default-web-root/mime.types

Judging by the ```This is a comment. I love comments.``` comment at the top of the previous version, this was borrowed from Apache.
Their copy has changed quite a bit since. Here's a repeatable step to obtain theirs:
```
wget -qO- http://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types > download.txt && \
head -n15 download.txt > mime.types && \
tail -n+16 download.txt | sed 's/^# //g' | sort | uniq >> mime.types && \
rm download.txt
```

latest mime.types

---

web-server-doc/web-server/scribblings/formlets.scrbl
web-server-lib/web-server/formlets/input.rkt
web-server-test/tests/web-server/formlets-test.rkt

I replaced #:display by #:wrap (since the latter allows the former), although it is obviously not backwards-compatible.

Add wrapper for radio input in radio-group

---

web-server-lib/web-server/formlets/input.rkt

Correcting the bug where only input-group had the #:wrap parameter, but not radio-group.
Again, didn't test it, as I need to figure out how to test my local branch.

Add #:wrap to radio-group (was added in input-group)

---

web-server-lib/web-server/formlets/input.rkt

This fixes the wrong contract that I built: `wrap` still returns a list of x-expressions, but the contract now reflects that. 
I tried to test the contract, but couldn't get it to fail on a (clearly wrong) contract, so this is again untested. 
I will try to find a way to run tests on my own branch, since me not doing so wasted quite a bit of time. Sorry about that.

Update/correct radio-group contract.

---

web-server-doc/web-server/scribblings/lang.scrbl

Changed the contract on the result to "any" (from "request?").

Corrected documentation for stateless "send/suspend/dispatch"

---

web-server-doc/web-server/scribblings/http.scrbl
web-server-lib/info.rkt
web-server-lib/web-server/http/response-structs.rkt

The contract on `response/output` demands that the provided function returns `void?`, which is needlessly restrictive, since it always ignores the result. Furthermore, this contract is actually even more pointless: it isn’t even enforced unless you use the `response/output` helper. The `response` struct is supposed to have the same contract on its `output`  field, but a typo in the contract uses `void` instead of `void?`, which permits any (single-valued) result.
This restriction is both annoying and actually confusing to people. It has come up on the mailing list before, and recently it came up again on the IRC channel. Furthermore, one of [Matt Might’s blog posts](http://matt.might.net/articles/low-level-web-in-racket/) actually depends on this permissive behavior of `response`, which …

Weaken the contract on response-output to permit any return value

---

web-server-doc/web-server/scribblings/http.scrbl
web-server-lib/web-server/http/id-cookie.rkt

in web-server/http/id-cookie
Also updates broken link to MIT Cookie Eaters

Uses crypto-random-bytes for make-secret-salt/file

---

web-server-doc/info.rkt
web-server-doc/web-server/scribblings/http.scrbl
web-server-lib/info.rkt
web-server-lib/web-server/http/cookie-parse.rkt
web-server-lib/web-server/http/cookie.rkt
web-server-lib/web-server/http/id-cookie.rkt
web-server-test/tests/web-server/http/cookies-test.rkt

Modifies web-server/http/cookie-parse, web-server/http/cookie,
and web-server/http/id-cookie to use net/cookies from the net-cookies
package, rather than the deprecated net/cookie.
resolves #20

Use RFC 6265 cookies from net-cookies

---

web-server-doc/web-server/scribblings/cache-table.scrbl
web-server-doc/web-server/scribblings/dispatch-servlets.scrbl
web-server-lib/web-server/dispatchers/dispatch-servlets.rkt
web-server-lib/web-server/private/cache-table.rkt
web-server-test/tests/web-server/private/cache-table-test.rkt

This PR makes backwards-compatible changes to both `make-cached-url->servlet` and `cache-table-clear!` to allow caches to be flushed selectively.

Selective cache flushing

---

web-server-doc/web-server/scribblings/http.scrbl
web-server-lib/web-server/http/id-cookie.rkt
web-server-test/tests/web-server/http/cookies-test.rkt

Adds a `#:shelf-life` argument to `valid-id-cookie?` and `request-id-cookie`.
The current `#:timeout` argument does something counterintuitive:
it requires that the cookie have been created *before* a certain
moment in time, effectively specifying a *minimum* age.
The new `#:shelf-life` argument supports specifying a maximum age.

Adds a `#:shelf-life` argument to `valid-id-cookie?`

---

web-server-doc/web-server/scribblings/dispatchers.scrbl
web-server-lib/web-server/dispatchers/dispatch.rkt

The contracts had previously been written using `void` (n.b. *not* `void?`).
Similar to https://github.com/racket/web-server/pull/17

Fix dispatcher/c and contract on next-dispatcher to use any

---

web-server-doc/web-server/scribblings/formlets.scrbl
web-server-lib/web-server/formlets/lib.rkt
web-server-test/tests/web-server/formlets-test.rkt

The old implementation of `formlet/c` could not actually handle multiple arguments. Expressions like `(formlet/c string? number?)` produced an error because `formlet/c` attempted to use `->` to define the processing function, but only `dynamic->*` can compute the number of results at runtime. The new implementation fixes this.
The new implementation is slightly more complicated because I wanted to avoid `dynamic->*` whenever possible, since it creates slower contracts than `->`. The obvious way is to make `formlet/c` a macro, but it was previously documented as being a function. I define `formlet/c` as a macro that expands to a function when it is used in a first-class context, and I have the function handle the one-argument case (i.e. all the uses of `formlet/c` that actually worked …

Fix formlet/c

---

web-server-doc/web-server/scribblings/formlets.scrbl
web-server-lib/web-server/formlets.rkt
web-server-lib/web-server/formlets/embed.rkt
web-server-lib/web-server/formlets/input.rkt
web-server-lib/web-server/formlets/lib.rkt
web-server-lib/web-server/formlets/stateless.rkt
web-server-lib/web-server/formlets/unsafe.rkt
web-server-lib/web-server/formlets/unsafe/dyn-syntax.rkt
web-server-lib/web-server/formlets/unsafe/embed.rkt
web-server-lib/web-server/formlets/unsafe/input.rkt
web-server-lib/web-server/formlets/unsafe/lib.rkt
web-server-lib/web-server/formlets/unsafe/stateless-send.rkt
web-server-lib/web-server/formlets/unsafe/syntax.rkt
web-server-test/tests/web-server/formlets-test.rkt
web-server-test/tests/web-server/formlets/stateless.rkt

1. The `web-server/formlets` library now produces formlets
that are `serializable?`, so it is now ok to have continuations
in `#lang web-server` that close over dynamically generated formlets.
2. Adds a library `web-server/formlets/serializable` that provides
a version of `send/formlet` using `send/suspend` from `#lang web-server`.
3. Offers `web-server/formlets/unsafe` for programmers who are willing to
forgo contract checking in exchange for the ability to capture
serializable continuations during the processing stage of formlets.
Closes https://github.com/racket/web-server/issues/23

Improves cooperation of formlets with #lang web-server

---

web-server-doc/web-server/scribblings/cache-table.scrbl
web-server-doc/web-server/scribblings/dispatch-servlets.scrbl
web-server-lib/web-server/dispatchers/dispatch-servlets.rkt
web-server-lib/web-server/private/cache-table.rkt
web-server-test/tests/web-server/private/cache-table-test.rkt

This PR adds an optional finalizer procedure both to the first result of `make-cached-url->servlet` and to `cache-table-clear!` in a backwards-compatible way.

Add optional finalizer procedure to flushed servlet instances

---

web-server-lib/web-server/http/response.rkt

This fixes an issue where, if the chunks of a chunked responses are too
short, they are never streamed to the client because they're buffered
within the OS socket.
A little more context here: https://racket.slack.com/archives/C06V96CKX/p1541782413390200

fix: flush chunks to client after every iteration

---

web-server-lib/web-server/default-web-root/mime.types

Browsers are now supporting ES6 (aka ES 2015) modules,
which must be served with with a JavaScript MIME type.
However, it is not always possible to determine if a file is a module
or a traditional script based on content alone,
so it is recommended to use the extension `.mjs`,
rather than `.js`, for clarity.
This commit adds `.mjs` as an extension for `text/javascript`,
which is the MIME type specified by the WHATWG HTML standard.
("Servers should use `text/javascript` for JavaScript resources.
Servers should not use other JavaScript MIME types for JavaScript
resources, and must not use non-JavaScript MIME types."
--- https://html.spec.whatwg.org/#scriptingLanguages )
Conservatively, it does not change the MIME type for `.js`,
which is currently mapped to `application/javascript`.
An IETF …

mime.types: add .mjs for JavaScript modules

---

web-server-lib/web-server/dispatch/syntax.rkt

Both `dispatch-rules` and `dispatch-rules+applies` yield functions that
generate URLs. There appear to be no tests to check what these URLs
are supposed to be like; here are a few.

Add tests for generated URLs

---

web-server-doc/web-server/scribblings/http.scrbl
web-server-doc/web-server/scribblings/lang.scrbl
web-server-doc/web-server/scribblings/web.scrbl
web-server-lib/web-server/http/redirect.rkt
web-server-lib/web-server/lang/web.rkt
web-server-lib/web-server/servlet/web.rkt

Previously, the `temporarily` status for `redirect-to`
meant the HTTP status `302 Found`, though this was
not guaranteed or documented.
For `302 Found` responses, user agents may use the same method as
the original request or may change the method from `POST` to `GET`.
This inconsistency is resolved by responding with `307 Temporary Redirect`
when the original method should always be used and
responding with `303 See Other` (which was already supported)
when the method should be changed from `POST` to `GET`,
e.g. for the Post-Redirect-Get pattern.
This commit changes the `temporarily` status for `redirect-to`
to mean `307 Temporary Redirect` and changes `redirect/get`
and `redirect/get/forget` to use the `see-other` status.
Also, the version of `redirect/get` from `#lang web-server`
is …

redirect-to and redirect/get: support 307 redirects

---

web-server-doc/web-server/scribblings/dispatch-servlets.scrbl

This pull request adds more documentation about the default finalization behavior of cached servlets provided by `make-cached-url->servlet`, fully resolving [this issue](https://github.com/racket/web-server/issues/34).

Add documentation to `make-cached-url-servlet`

---

web-server-doc/web-server/scribblings/running.scrbl
web-server-doc/web-server/scribblings/web-server.scrbl

I spotted a handful of problems in the web-server docs:
* typos
* parallelism problems
* words that probably ought to be typed out (@tt) because they're referring to formal parameters of a function or command-line invocation

Fix some typos in the web-server docs

---

web-server-doc/web-server/scribblings/cache-table.scrbl
web-server-doc/web-server/scribblings/dispatch-servlets.scrbl
web-server-doc/web-server/scribblings/dispatchers.scrbl
web-server-doc/web-server/scribblings/formlets.scrbl
web-server-doc/web-server/scribblings/http.scrbl
web-server-doc/web-server/scribblings/lang.scrbl
web-server-doc/web-server/scribblings/servlet-env.scrbl
web-server-doc/web-server/scribblings/templates.scrbl
web-server-doc/web-server/scribblings/web.scrbl
web-server-lib/info.rkt
web-server-lib/web-server/http/response-structs.rkt
web-server-lib/web-server/http/xexpr.rkt

Previously, both accepted `number?`, which was too permissive.
This commit adds `response-code/c`, which is defined as
`(integer-in 100 999)` per [RFC 2616 §6.1.1][1] ("The Status-Code
element is a 3-digit integer ...").
The contract for `response-seconds` is `real?`, which is the
range of `seconds->date` (which is used internally to generate the
`Last-Modified` header).
[1]: https://tools.ietf.org/html/rfc2616#section-6.1.1

strengthen contracts on `response-code` and `response-seconds`

---

web-server-doc/web-server/scribblings/http.scrbl
web-server-lib/info.rkt
web-server-lib/web-server/http/response-structs.rkt
web-server-lib/web-server/http/status-code.rkt
web-server-lib/web-server/http/xexpr.rkt

The various HTTP response-generating functions (`response/output`, `response/full`, and `response/xexpr`) currently require one to provide a status message, with `#"Okay"` serving as a default.
Supplying a status message in each call to `response/output` & friends is often inconvenient because, if one sticks to standard status codes, the status messages are usually a function of the code. In this pull request, I allow one to pass `#f` as the message. A message will be inferred from the code (which is required), with `#"OK"` serving as a fallback.
Existing code does not break. This change makes things more convenient going forward because one can omit one keyword argument in most cases. As before, it is always possible to supply a status message; if supplied, it will be used (the table of …

Offer a variety of default standard status HTTP response messages

---

web-server-doc/web-server/scribblings/http.scrbl
web-server-lib/info.rkt
web-server-lib/web-server/http.rkt
web-server-lib/web-server/http/json.rkt
web-server-lib/web-server/http/response-structs.rkt
web-server-test/tests/web-server/http/json.rkt
web-server-test/tests/web-server/http/util.rkt
web-server-test/tests/web-server/http/xexpr.rkt

In this pull request we add a new convenience function for generating JSON-laden HTTP responses. It is to JSON what `response/xexpr` is to XML.

Add new JSON convenience function à la response/xexpr

---

.github/workflows/ci.yml
README.md
web-server-test/tests/web-server/e2e/README.md
web-server-test/tests/web-server/e2e/all-e2e-tests.rkt
web-server-test/tests/web-server/e2e/echo/server.rkt
web-server-test/tests/web-server/e2e/echo/tests.rkt
web-server-test/tests/web-server/e2e/file-upload/server.rkt
web-server-test/tests/web-server/e2e/file-upload/tests.rkt
web-server-test/tests/web-server/e2e/json/server.rkt
web-server-test/tests/web-server/e2e/json/tests.rkt
web-server-test/tests/web-server/e2e/read-write/server.rkt
web-server-test/tests/web-server/e2e/read-write/tests.rkt
web-server-test/tests/web-server/e2e/tls/server.rkt
web-server-test/tests/web-server/e2e/tls/tests.rkt

I noticed how much additional work my last PR required (sorry @jeapostrophe !) to get working on drdr so I figured this repo could use CI of its own. [GH Actions](https://github.com/features/actions) are turning GA on November 13 and they're pretty convenient for this sort of thing.
You can see an example CI run [here](https://github.com/bogdanp/web-server/commit/c7855c4b3652190ff84a7803e11e9b01fbe27cb3/checks?check_suite_id=292872259).
EDIT: I added another commit to make the e2e tests wait for each server to become available before running their tests.

add CI via GitHub actions

---

.github/workflows/ci.yml
README.md
web-server-test/tests/web-server/e2e/read-write/tests.rkt

With this change, every push and pull request will be tested against both variants of Racket 7.4 as well as both variants of the latest snapshot.

ci: build against multiple Racket versions and variants

---

web-server-lib/web-server/http/request.rkt

It looks like some packages (eg. rfc6455) were depending on these despite them not being documented.
Closes #80.

request: provide read-headers and parse-bindings

---

web-server-doc/web-server/scribblings/http.scrbl
web-server-lib/web-server/http/empty.rkt

In some HTTP API settings (e.g., JSON RPC) it is convenient to provide empty HTTP responses. This change adds a little convenience, `response/empty`, for such responses.

Make empty responses

---

web-server-doc/web-server/scribblings/http.scrbl
web-server-lib/web-server/http.rkt

The documentation incorrectly implies that `response/empty`
is in the `web-server/http/response-structs` module.  You
can see this if you look at
https://docs.racket-lang.org/search/index.html?q=response%2Fempty
for 7.6. But this isn't true: if you use `response/empty` after `require`ing `web-server/http/response-structs`, you'll get an unbound identifier error. `response/empty` is actually provided from `web-server/http/empty`.
Rather than viewing this as a problem with the
documentation, the solution here is to incorporate
`response/empty`, which is currently defined in a little
module `empty.rkt`, into `response-structs.rkt`. It thus
sites alongside other utilities such as `response/full` and
`response/output`.

Move response/empty to http/request-structs.rkt.

---

.github/workflows/ci.yml
web-server-lib/web-server/private/timer.rkt
web-server-test/tests/web-server/private/connection-manager-test.rkt

This potentially fixes #88.
There were two issues:
* the tests relied on timing to work correctly and
* the connection object could be garbage collected before the timers
ran because the tests never used the connections.
I've changed the tests so they now synchronize based on events and
laid out the code so that the connections should be retained at least
for as long as needed for their timers to fire.

test: deflake connection-manager-test

---

web-server-doc/web-server/scribblings/dispatchers.scrbl
web-server-lib/web-server/dispatchers/dispatch-method.rkt
web-server-test/tests/web-server/dispatchers/dispatch-method.rkt

The purpose of this change is to be able to filter requests by their method.
Motivation: Many servers don't handle arbitrary HTTP methods, but only a handful of some standard ones; and even then, a smaller sub-handful of methods are the only ones that are actually supported (e.g., GET and HEAD only).
One can use `dispatch-rules` and variants thereof for fine-grained dispatching based on the request method.  But, to be complete, one ought to provide a fallback in every case (e.g., a request-method-not-allowed servlet, where the method matches `(regexp ".*")`.). Adding a request-method-not-allowed rule for every URL in `dispatch-rules` can decrease code readability. With the kind of functionality introduced here, one can say, at the outset, that all requests have a known HTTP method (e.g, …

New dispatcher constructor based on HTTP request method

---

web-server-doc/web-server/scribblings/http.scrbl
web-server-lib/web-server/http/status-code.rkt

Response code 206 is "Partial Content" and 308 is "Permanent
Redirect". According to the Mozilla trackers for these
codes,
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/206
and
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/308
206 appears to be supported across the board. 308 is largely
supported, though some old browsers may do the wrong thing
when given these codes. (The docs already mention this
caveat, and it makes sense to keep the notes there
unchanged.)
Nonetheless, this change should be OK. Adding support for
these codes does not mean that the web server starts
producing unexpected 308 responses. Rather, the change
amounts to this: if the web server is asked to render a
response in which the code is 206 or 308, it generates a
suitable status message. It was, …

Add response codes 206 and 308

---

web-server-lib/web-server/dispatchers/dispatch-servlets.rkt
web-server-lib/web-server/http/response.rkt
web-server-test/tests/web-server/e2e/all-e2e-tests.rkt
web-server-test/tests/web-server/e2e/head/server.rkt
web-server-test/tests/web-server/e2e/head/tests.rkt
web-server-test/tests/web-server/http/response-test.rkt

Norman Gray pointed out on the [mailing list][1] that responders don't gracefully handle the case where a response's output function throws an exception. Instead of truncating the response, they currently force the connection to hang until it times out or is closed by the client.
This PR "fixes" things so that responses are always terminated regardless of the state of the output function. I also liked @rmculpepper 's idea of intentionally breaking the response by writing a length w/o any follow-up content to make it clear that something went wrong to clients, but I'm not sure if any other web servers do that. I'll take a look at what other servers do tomorrow and report back.
After this change, this code:
```racket
#lang racket/base
(require web-server/http
web-server/servlet-dispatch …
```

response: terminate failed responses early in responder

---

web-server-lib/web-server/http/request.rkt
web-server-test/tests/web-server/private/fixtures/multipart-body-fields-without-data
web-server-test/tests/web-server/private/fixtures/multipart-body-realistic
web-server-test/tests/web-server/private/request-test.rkt

There is an edge case in the current implementation of `read-mime-multipart` that causes it to miss boundaries when the data is split in the middle of a boundary and the next boundary is in the buffer after the split. I've updated the tests to randomly chunk the fixtures, which made the error apparent, and fixed the implementation.

read-mime-multipart: fix content reading edge case

---

.github/workflows/ci.yml
web-server-lib/web-server/http/response.rkt
web-server-lib/web-server/private/connection-manager.rkt
web-server-lib/web-server/private/dispatch-server-with-connect-unit.rkt
web-server-lib/web-server/private/timer.rkt
web-server-lib/web-server/test.rkt
web-server-test/tests/web-server/http/json.rkt
web-server-test/tests/web-server/http/response-test.rkt
web-server-test/tests/web-server/http/xexpr.rkt
web-server-test/tests/web-server/private/connection-manager-test.rkt
web-server-test/tests/web-server/private/request-test.rkt
web-server-test/tests/web-server/private/response-test.rkt
web-server-test/tests/web-server/util.rkt

This change improves the web server's throughput with many (1k+) concurrent connections.  Of the bunch, the most important changes are those to the timer manager and the change to stop peeking in `handle-connection/cm`. I'd recommend looking at the commits individually for readability.
The change to `add-missing-headers` also fixes an issue: previously, the check if a header was already set on the response was case-sensitive.
On my local machine (macOS, 2.4GHz), [this app](https://gist.github.com/Bogdanp/b5ce64066fe6093da7e2ef70c3dab012) performs as follows when 4k requests per second are made for a minute after it's been warmed up:
* master:
```
$ cat targets | vegeta attack -duration=60s -rate 4000/s | vegeta report
Requests      [total, rate, throughput]         240000, 4000.02, …
```

core: optimize timers, conn handler and responses for throughput under high concurrency

---

web-server-lib/web-server/private/dispatch-server-with-connect-unit.rkt

Adds filesystem errno exceptions to the list of expected (harmless) exceptions, so that broken-pipe is correctly handled when coming from a unix domain socket.
Fixes #102

add filesystem:errno to expected exceptions (for unix domain sockets)

---

.github/workflows/ci.yml

I noticed in #103 that CI was failing due to some changes to the installer URI scheme so this fixes that problem.

ci: update racket versions and pin setup-racket@v1.5

---

web-server-lib/web-server/http/response-structs.rkt

The contract was overly strict. The intention all along was
to allow `#f` as the `#:message` argument. That's what's in
the docs, and indeed, we use `#f` in some tests.
closes #111

Fix contract for `response/output`

---

web-server-doc/web-server/scribblings/dispatchers.scrbl
web-server-lib/web-server/dispatchers/dispatch-wrap.rkt
web-server-test/tests/web-server/dispatchers/all-dispatchers-tests.rkt
web-server-test/tests/web-server/dispatchers/dispatch-wrap-test.rkt

A common pattern in web development is adding layers of request and response wrapping. That is, a web app often doesn't handle the original incoming request that hit the web server. Rather, it handles an enriched or otherwise transformed request. Similarly, the final response that ultimately gets serialized over the network may not be the response that the app emitted (after any initial request request transformations). As with requests, the final response may be the result of a chain of transformations.
As an example of all this, consider the task of injecting headers. Headers may be added (or changed, or dropped) from a request to store computed values that are needed further down the line. Authentication, for example, or processing cookies fits this pattern.
Another class of examples …

New wrapping dispatcher for transforming requests and responses

---

web-server-doc/web-server/scribblings/dispatchers.scrbl
web-server-lib/web-server/dispatchers/dispatch-files.rkt

We might want to set the response header based on path.
For example, a server might want to serve a gzip file (.gz) with
`Content-Encoding: gzip`, so that browsers automatically
unzip the file on the client side.

Add #:path->headers to dispatch-files

---

web-server-doc/web-server/scribblings/dispatchers.scrbl
web-server-lib/info.rkt

The previous PR (#117) should have bumped a version,
so that users who want to use #:path->headers can indicate
the version lower bound.

Bump version

---

web-server-doc/web-server/scribblings/safety-limits.scrbl
web-server-lib/info.rkt
web-server-lib/web-server/dispatchers/dispatch-log.rkt
web-server-lib/web-server/http/request-structs.rkt
web-server-lib/web-server/http/request.rkt
web-server-lib/web-server/http/response-structs.rkt
web-server-lib/web-server/http/response.rkt
web-server-lib/web-server/private/dispatch-server-sig.rkt
web-server-lib/web-server/private/dispatch-server-with-connect-unit.rkt
web-server-lib/web-server/private/timer.rkt
web-server-lib/web-server/safety-limits.rkt
web-server-lib/web-server/web-server.rkt
web-server-test/tests/web-server/e2e/max-concurrent/server.rkt
web-server-test/tests/web-server/e2e/max-concurrent/tests.rkt
web-server-test/tests/web-server/pr/12658.rkt
web-server-test/tests/web-server/private/request-test.rkt

I'm opening this as a draft in case folks want to weigh in on the changes. I've still got a few changes I want to make over the next couple weeks so this isn't quite ready yet. This PR includes the commit from #120, but that can be merged independently so it doesn't block #119.
The PR may be easier to read if you read the commits independently. I forgot @samth also worked on removing `run-server` until I looked at the list of open PRs just now, but I took that a little further by also improving the server loop in a couple ways so I think this PR supersedes #106.
Tested against the `/plaintext` endpoint of [this app](https://github.com/Bogdanp/FrameworkBenchmarks/blob/87870c5c1d746e8c253fdd3bf03e18eec4dafc69/frameworks/Racket/racket/app.rkt). Master branch:
```
Requests      [total, rate, …
```

more optimizations

---

web-server-doc/web-server/scribblings/dispatchers.scrbl
web-server-lib/info.rkt
web-server-lib/web-server/dispatchers/dispatch-log.rkt
web-server-lib/web-server/dispatchers/dispatch-logresp.rkt
web-server-lib/web-server/dispatchers/private/log.rkt
web-server-lib/web-server/http/response.rkt
web-server-lib/web-server/servlet-env.rkt
web-server-lib/web-server/web-server-unit.rkt
web-server-test/tests/web-server/dispatchers/dispatch-log-test.rkt
web-server-test/tests/web-server/dispatchers/dispatch-logresp-test.rkt

Add a new parameter `current-header-handler` which can be used
to transform the "header" (including code, message -- everything but the
body) right before it will be written to the output port.
Use this new parameter to implement `dispatch-logresp`, a new dispatcher
that consumes another dispatcher, and returns a dispatcher that acts
like the input dispatcher, except that if the input dispatcher is
dispatched, it will log request and response, just like how the
Apache server does.
Still need tests and documentation.
Partially fixes #54

Add current-header-handler and dispatch-logresp

---

web-server-doc/web-server/scribblings/dispatchers.scrbl
web-server-lib/web-server/dispatchers/dispatch-log.rkt
web-server-lib/web-server/dispatchers/dispatch-logresp.rkt
web-server-lib/web-server/dispatchers/private/log.rkt

The Combined Log Format adds "Referer" and "User-Agent" fields to the Apache default log format.
Compliance with the Combined Log Format definition is not 100%, as the size of the object returned to the client is missing, but this caveat is duly pointed out in the added docs.
Thanks for your work on Racket’s web server!

Add Combined Log Format option
